### ISSUE TITLE
Code mode stops when delegated task from orchestrator mode

### ISSUE THREAD

**Issue by ceotind** [Kilo-Org/kilocode#1746]
### Description

<img width="480" height="908" alt="Image" src="https://github.com/user-attachments/assets/0427d2ba-17e6-4cab-95dc-d41611a0f972" />
This is an issue faced many times today. When orchestrator mode delegates a task to code mode then it stops working and the resume button also does not shows up.

I have added several screenshots in the commit message 
https://github.com/Kilo-Org/kilocode/commit/b5a50d198306dcf24d16437ccf409e54fd3972cc

**Comment by ceotind** [comment]
<img width="479" height="933" alt="Image" src="https://github.com/user-attachments/assets/aee0b699-5ce3-4c92-97c7-31e98e08f0c4" />
Changed the model to and restarted orchestrator mode.
Code mode stopped again

**Comment by ceotind** [comment]
<img width="479" height="907" alt="Image" src="https://github.com/user-attachments/assets/ccf5a896-f8f2-4a1a-9915-7846543d9b21" />
I have tried this plenty of times. now will wait for the fix

**Comment by hassoncs** [comment]
Thank you for reporting this! I just merged in a fix an hour ago. It should be released shortly! https://github.com/Kilo-Org/kilocode/pull/1743

**Comment by hassoncs** [comment]
I'm going to close this since we think it should be fixed in `kilo-code@4.74.0`, but please re-open if you are still running into issues!
https://github.com/Kilo-Org/kilocode/pull/1737

**Comment by ceotind** [comment]
<img width="482" height="1037" alt="Image" src="https://github.com/user-attachments/assets/546ebe32-2232-489a-b3d7-d99457d14b91" />
The issue is not resolved
I am on the latest version 4.74.0

Orchestrator mode was running fine before the recent commits

**Comment by ceotind** [comment]
@chrarnoldus please open the issue

**Comment by kevinvandijk** [comment]
Can confirm there are still issues. Might or might nog be related but when delegating to a subtask often the first API request keeps spinning forever, needs a cancel and resume click for it to continue

**Comment by ceotind** [comment]
Using 4.72.1 and orchestrator mode is working better. Just once it showed the issue 

But 4.74.0 is unusable at all with orchestrator mode

**Comment by ceotind** [comment]
issue seems to be present with architect mode as well when the task is delegated to code mode.

**Comment by ceotind** [comment]
any update on this @chrarnoldus @kevinvandijk ??

**Comment by ceotind** [comment]
<img width="485" height="650" alt="Image" src="https://github.com/user-attachments/assets/1117fbcb-17ff-47ae-8b33-23b967805e4b" />
This proves that the issue is with architect mode as well.
Currently I am in the latest version 4.75.0

**Comment by ceotind** [comment]
<img width="480" height="933" alt="Image" src="https://github.com/user-attachments/assets/4eb42d8f-16e0-4158-abbf-e5c2b128da85" />

Working with the latest version and yet the issue is not resolved in orchestrator mode as well

**Comment by ceotind** [comment]
<img width="480" height="940" alt="Image" src="https://github.com/user-attachments/assets/0ff0082e-f839-4639-bcf4-09f4ded0bb89" />
Architect mode stopped at this point 
this is the first prompt

**Comment by ceotind** [comment]
<img width="480" height="940" alt="Image" src="https://github.com/user-attachments/assets/18bffdbe-4291-43e7-aaab-0af504fa7010" />

again in architect mode when task is delegated to code mode

**Comment by kevinvandijk** [comment]
This should be fixed by https://github.com/Kilo-Org/kilocode/pull/1792 
Nobody here seems to be able to reproduce it anymore but if you still experience this @ceotind feel free to re-open the issue again and we'll take another look!

**Comment by ceotind** [comment]
I believe it is fixed.
